version: "3.6"

services:

  app:
    container_name: app
    image: nginx
    
  app_proxy:
    container_name: app_proxy
    image: nginx
    ports:
      - 443:443
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ${PWD}/ca.crt:/etc/nginx/client_certs/ca.crt
